services:
  Rollbar\Symfony\RollbarBundle\EventListener\ExceptionListener:
    arguments:
      - '@service_container'
      - '@logger'
      - '@Rollbar\Symfony\RollbarBundle\Payload\Generator'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: -100 }

#   symfony_rollbar.event_listener.error_listener:
#     class: SymfonyRollbarBundle\EventListener\ErrorListener
#     arguments: ["@service_container"]
#     tags:
#       - { name: kernel.event_listener, event: kernel.exception }

  Rollbar\Symfony\RollbarBundle\Factories\RollbarHandlerFactory: ~

  Rollbar\Monolog\Handler\RollbarHandler:
    factory: 'Rollbar\Symfony\RollbarBundle\Factories\RollbarHandlerFactory:createRollbarHandler'
    arguments:
      - '@service_container'
    tags:
      - { name: monolog.logger, channel: rollbar }

  Rollbar\Symfony\RollbarBundle\Payload\Generator:
    arguments:
      - '@service_container'