language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php -v
  - php composer.phar test

after_success:
    - bash <(curl -s https://codecov.io/bash)
