parameters:
  symfony_rollbar.event_listener.exception_listener.class: SymfonyRollbarBundle\EventListener\ExceptionListener
  symfony_rollbar.event_listener.error_listener.class: SymfonyRollbarBundle\EventListener\ErrorListener

services:
  symfony_rollbar.event_listener.exception_listener:
          class: SymfonyRollbarBundle\EventListener\ExceptionListener
          arguments: ["@service_container"]
          tags:
              - { name: kernel.event_listener, event: kernel.exception, priority: -100 }

  symfony_rollbar.event_listener.error_listener:
            class: SymfonyRollbarBundle\EventListener\ErrorListener
            arguments: ["@service_container"]
