parameters:
  symfony_rollbar.event_listener.exception_listener.class: SymfonyRollbarBundle\EventListener\ExceptionListener

services:
  symfony_rollbar.event_listener.exception_listener:
          class: SymfonyRollbarBundle\EventListener\ExceptionListener
          arguments: ["@service_container"]
          tags:
              - { name: kernel.event_listener, event: kernel.exception, priority: -100 }
